- name: "Save Config"
  hosts: Cisco
  gather_facts: false

  tasks:
    - name: Show run
      ios_command:
        commands:
          - show run
      register: config

    - set_fact: time="{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"

    - name: Save Output
      connection: local
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "/home/backup/devcisco/{{ inventory_hostname }}_run_cfg_{{ time }}.txt"
